name: 'Composer Install'
description: 'Run `composer install`'

runs:
  using: composite
  steps:
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
      shell: bash
