version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Taipei"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Taipei"
