name: 'Prepare Laravel'
description: 'Prepare Laravel'

runs:
  using: composite
  steps:
    - name: Copy .env
      run: cp .github/.env.github .env
      shell: bash

    - name: Generate key
      run: php artisan key:generate
      shell: bash

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      shell: bash
