name: Symfony Security Advisories

on:
  push:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 12 * * *'

jobs:
  symfony-security-advisories:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-db
        with:
            path: ~/.symfony/cache
            key: db
      - uses: symfonycorp/security-checker-action@v2
